[build]
  publish = "."
  command = ""

# Redirect root to launch.html
[[redirects]]
  from = "/"
  to = "/launch.html"
  status = 200

# Handle all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 